### ISSUE TITLE
AngularJS links actually point to an Angular (angular2) blog post

### ISSUE THREAD

**Issue by nchudleigh** [hasura/awesome-live-reloading#5]
The distinction between AngularJS (v1) and Angular (v2+) is not made here and some may find it confusing.

**Comment by malkia** [comment]
On the Angular2 (+) front there is the TypeScript, and Dart versions. They surely do have different (and on Dart side more than one) live update techniques (dartium, now legacy, and dartdevc now).

**Comment by wawhal** [comment]
Thanks for pointing @nchudleigh @malkia .
Does one of you know a more apt blogpost for Angular and Webpack? I would really appreciate it if you make a pull request.
